name: Build
on:
  push:
  pull_request:
  repository_dispatch:

env:
  NODE_VERSION: 16.x
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    # always run in pull request, or repository_dispatch. Otherwise (push, etc.) don't run if commit message is skipping CI
    if: github.event_name == 'pull_request' || github.event_name == 'repository_dispatch' || (!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]'))
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore NPM cache
        uses: actions/cache@v3
        continue-on-error: true
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - run: npm test

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: test
    # only run if in main. If repository_dispatch always run, else if `schedule` or `push`, only run if not skipping CI
    if: github.ref == 'refs/heads/main' && (github.event_name == 'repository_dispatch' || (github.event_name == 'schedule' || github.event_name == 'push') && (!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')))
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore NPM cache
        uses: actions/cache@v3
        continue-on-error: true
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        # only publish if a direct `push`/`repository_dispatch`
        if: github.event_name == 'repository_dispatch' || github.event_name == 'push'
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: "publish"
